### ISSUE TITLE
MaxpoolNMS

### ISSUE THREAD

**Issue by kossolax** [hoya012/deep_learning_object_detection#18]
I can't find this paper:

[MaxpoolNMS] MaxpoolNMS: Getting Rid of NMS Bottlenecks in Two-Stage Object Detectors | [CVPR' 19]

 Do you have a link to share please ? 
Thanks.

**Comment by hoya012** [comment]
Hello,
Some of the accepted paper of CVPR 2019 was not disclosed. It will be added when it becomes public.
