### ISSUE TITLE
deep_learning_object_detection_history.PNG missing

### ISSUE THREAD

**Issue by chensonglu** [hoya012/deep_learning_object_detection#25]
@hoya012 deep_learning_object_detection_history.PNG cannot be displayed.

**Comment by hoya012** [comment]
I can see that. I think there is no problem. Let's refresh(F5) .If still not be displayed, please tell me. Thanks.

**Comment by chuxiang93** [comment]
I can't see the figure, too. Although i can see the figure after downloading the project. Maybe something is wrong...
![image](https://user-images.githubusercontent.com/11666931/68109366-55cecd80-ff25-11e9-87ef-d8eecde7267d.png)

**Comment by hoya012** [comment]
![image](https://user-images.githubusercontent.com/37167578/68118586-afde8b80-ff43-11e9-9b18-1e9898c039d7.png)

i don't know exactly.. sorry.

i tried various pc, phone, any web browser, but i can see that.. so i upload picture in this comment.

**Comment by chensonglu** [comment]
@hoya012 thanks.
