### ISSUE TITLE
Time to update~

### ISSUE THREAD

**Issue by TaoXieSZ** [hoya012/deep_learning_object_detection#28]
Dear author,

It's May!

Expecting for you update

**Comment by hoya012** [comment]
Forgive me for being late. I am late waiting for the list of CVPR acceted paper.

In addition, i will share the data analyzing the trend of CVPR 2020. Please also refer to this document.

CVPR-2020-Paper-Statistics: https://github.com/hoya012/CVPR-2020-Paper-Statistics
