### ISSUE TITLE
add some links

### ISSUE THREAD

**Issue by XuVision** [hoya012/deep_learning_object_detection#31]
[Dynamic R-CNN] https://arxiv.org/pdf/2004.06002.pdf
[Arbitrary-Oriented Object Detection with
Circular Smooth Label] https://arxiv.org/pdf/2003.05597.pdf
[LabelEnc] https://arxiv.org/pdf/2007.03282.pdf
[Probabilistic Anchor Assignment with IoU
Prediction for Object Detection] https://arxiv.org/pdf/2007.08103.pdf
[Soft Anchor-Point Object Detection] https://arxiv.org/pdf/1911.12448.pdf
[GeoGraph] https://arxiv.org/pdf/2003.10151.pdf
[Highly Efficient Salient Object Detection with
100K Parameters] https://arxiv.org/pdf/2003.05643.pdf
[Prior-based Domain Adaptive Object Detection
for Hazy and Rainy Conditions] https://arxiv.org/pdf/1912.00070.pdf
[Cheaper Pre-training Lunch] https://arxiv.org/pdf/2004.12178.pdf
[Side-Aware Boundary Localization for More Precise Object Detection] https://arxiv.org/pdf/1912.04260.pdf
[Domain Adaptive Object Detection via
Asymmetric Tri-way Faster-RCNN] https://arxiv.org/pdf/2007.01571.pdf
[HoughNet] https://arxiv.org/pdf/2007.02355.pdf
[OS2D] https://arxiv.org/pdf/2003.06800.pdf
[Adaptive Object Detection with Dual Multi-Label Prediction] https://arxiv.org/pdf/2003.12943.pdf
[Boosting Weakly Supervised Object Detection
with Progressive Knowledge Transfer] https://arxiv.org/pdf/2007.07986.pdf
[APRICOT] https://arxiv.org/pdf/1912.08166.pdf

**Comment by hoya012** [comment]
I will add them! Thank you very much!
