### ISSUE TITLE
Add FPS in the performance table

### ISSUE THREAD

**Issue by MohamedAliRashad** [hoya012/deep_learning_object_detection#6]
It will be a great help for people with real time applications in mind and want a comparison between the latest papers in this area.

**Comment by hoya012** [comment]
I think so too. However, it is a difficult issue because FPS information is not included in all papers. But I will add and appreciate the good feedback. Thank You!!

**Comment by MohamedAliRashad** [comment]
I can try and help you with this but the problem is that we need a unified test measure for this .... Any ideas ??

**Comment by hoya012** [comment]
I was worried that the FPS index is related to the hardware spec(e.g. CPU, GPU, RAM, etc), so it is hard to make an equal comparison. The solution is to measure the performance of all models on hardware with equivalent specifications, but it is very difficult and time consuming..
