### ISSUE TITLE
Question about "paper list from 2014 to now(2019)"

### ISSUE THREAD

**Issue by crcrpar** [hoya012/deep_learning_object_detection#7]
Thank you for your fantastic & easy-to-read repo!

Could you tell me why some models like SSD and YOLO are written in red characters?

**Comment by hoya012** [comment]
Hello!, 
The part highlighted with red characters means papers that i think "must-read".
However, it is my **personal** opinion and other papers are important too, so I recommend to read them if you have time. 
Thanks!

**Comment by crcrpar** [comment]
Thank you for your reply.

As a newbie to object detection, this must-read list is so helpful!
