### ISSUE TITLE
Peleenet's results in voc(07+12) is wrong.

### ISSUE THREAD

**Issue by weiyaowu-md** [hoya012/deep_learning_object_detection#9]
In that paper, the result of pelee training on voc0712 is 70.9, not 76.4 that first train on  coco trainval35k then fine_tune on 07+12
![image](https://user-images.githubusercontent.com/25010151/52159789-44ca0500-26e4-11e9-9bf1-f8a12f0eafbd.png)

**Comment by hoya012** [comment]
i will change! thanks!
